### ISSUE TITLE
Move auto-generated templates to own repo?

### ISSUE THREAD

**Issue by gsaslis** [3scale/3scale-operator#11]
Do you think it makes sense to move the auto-generated templates in a separate repository?

I was trying to put together some instructions for a quick evaluation / deployment on my minishift and using [3scale/3scale-operator/pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml](https://raw.githubusercontent.com/3scale/3scale-operator/master/pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml) seems a little bit... obscure / non-obvious. 

Perhaps there are some other plans around this already?

/cc @miguelsorianod

**Comment by miguelsorianod** [comment]
At this stage of the development I'm inclined to not move the autogenerated templates.
The main reasons are:
* Publicly released productized templates are already in another repository (https://github.com/3scale/3scale-amp-openshift-templates) (I'm aware that those are only the released templates)
* For the usage of development templates I don't want to separate the generation code from the generated templates in different repositories because each change made in the source code of the generator would imply opening a PR in each repository, and it would be hard to track related changes and very error-prone. We want to minimize the number of repositories that play into this.
* Templates will eventually stop being used when Operator is stable

I'm thinking on moving the generated templates to a not-so-obscure directory in the same repository but I'm not going to do it until I have a more clear image on how the operator is going to be structured, or some need arises (CI/QE-related).

**Comment by gsaslis** [comment]
I see, thanks. 

I would be ok with a simple `git commit ... && git push` to another repo on merge to master (i.e. no PRs involved - it is all automated and will run after some PR to this repo anyway). 

that repo could very well be https://github.com/3scale/3scale-amp-openshift-templates btw  ;)
