### ISSUE TITLE
DeploymentConfigs do not rollout

### ISSUE THREAD

**Issue by mrhillsman** [3scale/3scale-operator#213]
OpenShift 4.1.11
Kubernetes v1.13.4+df9cebc

Steps to reproduce:
* Create project (3scale)
* Install 3scale operator via OperatorHub
  * OpenShift > Catalog > OperatorHub > 3scale Operator > Install
* Create APIManager instance
  * OpenShift > Catalog > Installed Operators > 3scale Operator > API Manager > Create APIManager

API Manager created with the following details:

apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimgr
  namespace: 3scale
spec:
  wildcardDomain: <<valid wildcard domain for openshift cluster was put here>>

No pods are actually ever created. When checking the logs for the ImageStream referenced by one of the DeploymentConfig the status returned is:

status:
  dockerImageRepository: 'image-registry.openshift-image-registry.svc:5000/3scale/amp-apicast'
  tags:
    - tag: '2.6'
      items: null
      conditions:
        - type: ImportSuccess
          status: 'False'
          lastTransitionTime: '2019-08-26T16:18:14Z'
          reason: InternalError
          message: >-
            Internal error occurred: Get
            https://registry.redhat.io/v2/3scale-amp26/apicast-gateway/manifests/latest:
            unauthorized: Please login to the Red Hat Registry using your
            Customer Portal credentials. Further instructions can be found here:
            https://access.redhat.com/articles/3399531
          generation: 2

In order to resolve this the sample-registry-credentials secret from the openshift namespace was copied to the 3scale registry.

A potential solution would be to have the operator during install grab the secret and store it as a secret or configmap for use when the operator resources (API Manager in this case) are instantiated within the namespace the operator is run in.

**Comment by miguelsorianod** [comment]
Hi @mrhillsman,

In order to be able to pull the images, a secret with a specific name ("threescale-registry-auth") containing the registry.redhat.io credentials must be created.

This is documented in the installation guide of the new 3scale 2.6 version:
https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.6/html/installing_3scale/onpremises-installation#deploying-threescale-using-the-operator

**Comment by miguelsorianod** [comment]
Hi @mrhillsman,

3scale 2.6 release was publicly released and announced last week and the previous issue was created before last week.

The need of the registry credentials totally depends on which version of the operator are you using.

The registry credentials requirement is a new change of the 3scale 2.6 productised version because productised images now require the use of the new registry.redhat.io authenticated registry. In 2.5 you did not find this problem because for that release the images were not in the new repository.

The officially supported installation method for the productised 3scale-operator is through OLM. In case you are using the productised 3scale-operator version you should use the official RedHat documentation as with any other RedHat product. In this case the link provided in my previous comment.

When you say "on the installation" page what do you mean? In the official 3scale product documentation link for 3scale 2.6, which is the one  provided before it is documented as a prerequisite and contains references to how the secret can be created:
https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.6/html/installing_3scale/onpremises-installation#deploying-threescale-using-the-operator

If you want to deploy the productised version of the 3scale-operator you should do it through OLM in OpenShift 4.x as explained in the official RedHat documentation.

If you are using a git branch that is not of a productised version (the numbered branches that do not end in '-prod') you are using a non-productised("community") version of the operator and that does not need the credentials as it uses public repositories for the images. Keep in mind though that then you would not be using a productised version of the operator (the officially-provided RedHat product) if that was your intention, hence why it is not documented in the GitHub repository.

Regarding the broken link, can you point me where is that broken link so we can review it and fix it?

Thank you.

**Comment by mrhillsman** [comment]
Hey @miguelsorianod sorry so late; did not get a notification of your mention. I attached an image of where the bad link can be found; it is in the OpenShift Operatorhub. It points to https://github.com/3scale/3scale-operator/blob/v0.3.0/doc/user-guide.md which now is resolved but was not at the time of the issue of course. So you can disregard.


![3scale_doc_link_error](https://user-images.githubusercontent.com/3989695/64449203-085cee00-d0a5-11e9-9664-83b17714651e.png)
