### ISSUE TITLE
Support Postgres 14 and SCRAM by upgrading to libpq version 10 or above.

### ISSUE THREAD

**Issue by dlydiard** [3scale/3scale-operator#823]
The POD `system-app-1-hook-pre` fails to run successfully when using an external postgres database on version 14.5.

The logs report the following error:
```
PG::ConnectionBad: SCRAM authentication requires libpq version 10 or above
```

as a workaround i set the default `password_encryption` to `md5` on the postgres cluster and changed the ROLE passwords, and `system-app-1-hook-pre` ran successfully.

Please support SCRAM authentication as it's a more secure auth method, thanks!

**Comment by eguzki** [comment]
The 3scale operator can be anhanced to deploy (not recommended for production) Postgresql 14. Currently (2.13) the supported version is PostgreSQL 13 (From https://access.redhat.com/articles/279852)

But first, the [Porta](https://github.com/3scale/porta) component (aka System) needs to support PostgreSQL 14. This issue is all about Porta supporting Postgresql 14, thus I think it should be opened in https://github.com/3scale/porta.

**Comment by dlydiard** [comment]
doesn't look like the Porta repo takes issues (at least for me).

**Comment by eguzki** [comment]
You should then open a [jira issue](https://issues.redhat.com/projects/THREESCALE/issues) and set `System` as the Component

**Comment by dlydiard** [comment]
Thanks, issue opened: https://issues.redhat.com/browse/THREESCALE-9706
